apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-profile
  template:
    metadata:
      labels:
        app: user-profile
    spec:
      containers:
      - name: user-profile
        image: registryuqk1141.azurecr.io/tripinsights/user-java:v1
        env:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 80
        volumeMounts:
        - name: sqlserver
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: sqlserver
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: kvcreds                  # [OPTIONAL] not required if using Pod Identity
          options:
            usepodidentity: "false"        # [OPTIONAL] if not provided, will default to "false"
            keyvaultname: "team1vault"               # the name of the KeyVault
            keyvaultobjectnames: sqlpassword;sqlsrvhost;sqluser    # list of KeyVault object names (semi-colon separated)
            keyvaultobjectaliases: SQL_PASSWORD;SQL_SERVER;SQL_USER
            keyvaultobjecttypes: secret;secret;secret  # list of KeyVault object types: secret, key or cert (semi-colon separated)
            resourcegroup: "teamResources"              # [REQUIRED FOR < v0.0.14] the resource group of the KeyVault
            subscriptionid: "32b1e906-77c9-4cf8-be19-0cf26d5f8cc7"             # [REQUIRED FOR < v0.0.14] the subscription ID of the KeyVault
            tenantid: "f5929c31-d5e2-4e95-b56c-569be05a0760"                   # the tenant ID of the KeyVault
