apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: trip-viewer-ingress
  namespace: web-dev
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: tripviewer-service
          servicePort: 80
        path: /