apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: api-ingress
  namespace: api-dev
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: trips-service
          servicePort: 80
        path: /api/trips
      - backend:
          serviceName: poi-service
          servicePort: 80
        path: /api/poi
      - backend:
          serviceName: user-profile-java-service
          servicePort: 80
        path: /api/user-java
      - backend:
          serviceName: user-profile-js-service
          servicePort: 80
        path: /api/user