apiVersion: v1
kind: Service
metadata:
  name: user-profile-java-service
  namespace: api-dev
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: user-profile-java-api