apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-profile-java-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-profile-java-api
  template:
    metadata:
      labels:
        app: user-profile-java-api
    spec:
      containers:
      - name: user-profile-java-api
        image: registryamd4608.azurecr.io/tripinsights/user-java:1.0
        env:
          - name: SQL_USER
            value: "<sql user name>"
          - name: SQL_PASSWORD
            value: "<password>"
          - name: SQL_SERVER
            value: "<sql server>.database.windows.net"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 80
