kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-web-dev-ns-policy
  namespace: api-dev
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
  - from: 
    - namespaceSelector:
        matchLabels:
          environment: web-dev
      podSelector:
        matchLabels: 
          app: tripviewer
  egress:
  - {}